[package]
name = "rccheck"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Francois Garillot <francois@mystenlabs.com>"]
description = "tools for rustls-based certificate verification using pre-shared public keys"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = false

[dependencies]
rustls = { version = "0.20.6", default-features = false, features = ["logging", "dangerous_configuration"] }
serde = { version = "1.0.138", features = ["derive"] }
tracing = "0.1.35"
webpki = { version = "0.22.0", features = ["alloc", "std"] }
x509-parser = "0.13.0"
rcgen = "0.9.2"
anyhow = "1.0.58"
ed25519-dalek = "1.0.1"
ed25519 = { version = "1.5.2", features = ["pkcs8", "alloc", "zeroize"] }
pkcs8 = { version = "0.9.0", features = ["std"] }
ouroboros = "0.15.0"

[dev-dependencies]
bincode = "1.3.3"
proptest = "1.0.0"
rand = "0.7.3"
