[package]
name = "rccheck"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Francois Garillot <francois@mystenlabs.com>"]
description = "tools for rustls-based certificate verification using pre-shared public keys"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = false

[dependencies]
ed25519 = { version = "1.5.2", features = ["pkcs8", "alloc", "zeroize"] }
ed25519-dalek = "1.0.1"
eyre = "0.6.8"
ouroboros = "0.15.1"
pkcs8 = { version = "0.9.0", features = ["std"] }
rcgen = { version = "0.10.0", features = ["x509-parser"] }
rustls = { version = "0.20.6", default-features = false, features = ["logging", "dangerous_configuration"] }
serde = { version = "1.0.140", features = ["derive"] }
tracing = "0.1.36"
webpki = { version = "0.22.0", features = ["alloc", "std"] }
x509-parser = "0.14.0"

[dev-dependencies]
bincode = "1.3.3"
proptest = "1.0.0"
rand = "0.7.3"

[env]
COMMON_DISTINGUISHED_NAME = "NARWHAL"
