[package]
name = "typed-store-derive"
version = "0.0.0"
license = "Apache-2.0"
authors = ["Ade A. <ade@mystenlabs.com>"]
description = "macros for typed store"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = false

[lib]
proc-macro = true

[dependencies]
eyre = "0.6.8"
fdlimit = "0.2.1"
pre = "0.2.0"
proc-macro2 = "1.0.24"
quote = "1.0.9"
rocksdb = { version = "0.19.0", features = ["snappy", "lz4", "zstd", "zlib", "multi-threaded-cf"], default-features = false }
syn = { version = "1.0.64", features = ["derive"] }
tempfile = "3.3.0"
tokio = { version = "1.20.0", features = ["sync", "macros", "rt"] }
typed-store = { path = "../typed-store" }
