[package]
name = "typed-store"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Francois Garillot <francois@mystenlabs.com>"]
description = "a typed database interface"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"

[dependencies]
# deactivation of bzip2 due to https://github.com/rust-rocksdb/rust-rocksdb/issues/609
rocksdb = { version = "0.18.0", features = ["snappy", "lz4", "zstd", "zlib"], default-features = false }
eyre = "0.6.5"
serde = { version = "1.0.133", features = ["derive"]}
bincode = "1.3.3"
tokio = { version = "1.15.0", features = ["sync", "macros", "rt"] }
thiserror = "1.0.30"
collectable = "0.0.2"

[dev-dependencies]
tempfile = "3.3.0"
