[workspace]
members = [
    "component",
    "crates/x",
    "name-variant",
    "rccheck",
    "telemetry-subscribers",
    "typed-store",
]

[profile.release]
codegen-units = 1
lto = true

[profile.bench]
codegen-units = 1
lto = true
