[workspace]
members = [
    "anemo",
    "component",
    "name_variant",
    "rccheck",
    "telemetry_subscribers",
    "typed-store",
]

[profile.release]
codegen-units = 1
lto = true

[profile.bench]
codegen-units = 1
lto = true
