[package]
name = "telemetry-subscribers"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Evan Chan <echan@mystenlabs.com>"]
description = "Library for common telemetry and observability functionality"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = false

[dependencies]
tokio = { version = "1.19.2", features = ["sync", "macros", "rt", "rt-multi-thread"] }
tracing = "0.1.35"
tracing-appender = "0.2.2"
tracing-subscriber = { version = "0.3.14", features = ["std", "time", "registry", "env-filter"] }
tracing-bunyan-formatter = "0.3.3"
tracing-opentelemetry = { version = "0.17.4", optional = true }
opentelemetry = { version = "0.17.0", features = ["rt-tokio"], optional = true }
opentelemetry-jaeger = { version = "0.16.0", features = ["rt-tokio"], optional = true }
console-subscriber = { version = "0.1.6", optional = true }
tracing-chrome = { version = "0.6.0", optional = true }
once_cell = "1.12.0"
crossterm = "0.24.0"

[features]
default = ["jaeger", "chrome"]
tokio-console = ["console-subscriber"]
jaeger = ["tracing-opentelemetry", "opentelemetry", "opentelemetry-jaeger"]
chrome = ["tracing-chrome"]

[dev-dependencies]
camino = "1.0.9"
