[package]
name = "telemetry-subscribers"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Evan Chan <echan@mystenlabs.com>"]
description = "Library for common telemetry and observability functionality"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = false

[dependencies]
chrono = "0.4.0"
console-subscriber = { version = "0.1.6", optional = true }
crossterm = "0.25.0"
once_cell = "1.13.0"
opentelemetry = { version = "0.17.0", features = ["rt-tokio"], optional = true }
opentelemetry-jaeger = { version = "0.16.0", features = ["rt-tokio"], optional = true }
prometheus = "0.13.1"
tokio = { version = "1.20.1", features = ["sync", "macros", "rt", "rt-multi-thread"] }
tracing = "0.1.36"
tracing-appender = "0.2.2"
tracing-bunyan-formatter = "0.3.3"
tracing-chrome = { version = "0.6.0", optional = true }
tracing-opentelemetry = { version = "0.17.4", optional = true }
tracing-subscriber = { version = "0.3.15", features = ["std", "time", "registry", "env-filter"] }

[features]
default = ["jaeger", "chrome"]
tokio-console = ["console-subscriber"]
jaeger = ["tracing-opentelemetry", "opentelemetry", "opentelemetry-jaeger"]
chrome = ["tracing-chrome"]

[dev-dependencies]
camino = "1.0.9"
