[package]
name = "x"
version = "0.1.0"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.58"
clap = { version = "3.1.14", features = ["derive"] }
nexlint = { git = "https://github.com/nextest-rs/nexlint.git", rev = "5bf35a12bfaed45328288933e222006ee4e99c28" }
nexlint-lints = { git = "https://github.com/nextest-rs/nexlint.git", rev = "5bf35a12bfaed45328288933e222006ee4e99c28" }
