[package]
name = "typed-store"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Francois Garillot <francois@mystenlabs.com>"]
description = "a typed database interface"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = ["crates-io"]

[dependencies]
bincode = "1.3.3"
collectable = "0.0.2"
eyre = "0.6.8"
fdlimit = "0.2.1"
once_cell = "1.15.0"
tap = "1.0.1"
prometheus = "0.13.2"
# deactivation of bzip2 due to https://github.com/rust-rocksdb/rust-rocksdb/issues/609
rocksdb = { version = "0.19.0", features = ["snappy", "lz4", "zstd", "zlib", "multi-threaded-cf"], default-features = false }
serde = { version = "1.0.140", features = ["derive"] }
thiserror = "1.0.31"
tokio = { version = "1.20.1", features = ["sync", "macros", "rt"] }
tracing = "0.1.36"

[dev-dependencies]
tempfile = "3.3.0"
once_cell = "1.13.0"
proc-macro2 = "1.0.24"
quote = "1.0.9"
syn = { version = "1.0.64", features = ["derive"] }
typed-store-derive = {path = "../typed-store-derive"}
