[package]
name = "typed-store-macros-tests"
version = "0.0.0"
license = "Apache-2.0"
authors = ["Ade A. <ade@mystenlabs.com>"]
description = "tests for macros for typed store"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = false

[dev-dependencies]
bincode = "1.3.3"
collectable = "0.0.2"
eyre = "0.6.8"
fdlimit = "0.2.1"
pre = "0.2.0"
once_cell = "1.13.0"
proc-macro2 = "1.0.24"
quote = "1.0.9"
rocksdb = { version = "0.19.0", features = ["snappy", "lz4", "zstd", "zlib", "multi-threaded-cf"], default-features = false }
serde = { version = "1.0.139", features = ["derive"] }
syn = { version = "1.0.64", features = ["derive"] }
tempfile = "3.3.0"
thiserror = "1.0.31"
tokio = { version = "1.20.0", features = ["sync", "macros", "rt"] }
tracing = "0.1.35"
typed-store = { path = "../typed-store" }
typed-store-macros = { path = "../typed-store-macros" }

[dependencies]
eyre = "0.6.8"
