[package]
name = "typed-store-macros-tests"
version = "0.0.0"
license = "Apache-2.0"
authors = ["Ade A. <ade@mystenlabs.com>"]
description = "tests for macros for typed store"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"
publish = false


[dev-dependencies]
syn = { version = "1.0.64", features = ["derive"] }
quote = "1.0.9"
proc-macro2 = "1.0.24"
anyhow = { version = "1.0.58", features = ["backtrace"] }
typed-store = {path = "../typed-store"}
tempfile = "3.3.0"
tokio = { version = "1.20.0", features = ["sync", "macros", "rt"] }
typed-store-macros = { path = "../typed-store-macros"}
rocksdb = { version = "0.18.0", features = ["snappy", "lz4", "zstd", "zlib", "multi-threaded-cf"], default-features = false }
eyre = "0.6.8"
serde = { version = "1.0.139", features = ["derive"] }
bincode = "1.3.3"
tracing = "0.1.35"
thiserror = "1.0.31"
collectable = "0.0.2"
fdlimit = "0.2.1"