[package]
name = "name-variant"
version = "1.0.0"
authors = ["Francois Garillot <francois@mystenlabs.com>"]
edition = "2021"
description = "Generates a method to name enum variants."
license = "Apache-2.0"
repository = "https://github.com/mysten_infra/name_variant"
publish = false

[lib]
proc-macro = true

[dependencies]
syn = "1.0.98"
quote = "1.0.20"
proc-macro2 = "1.0.40"
