[package]
name = "name-variant"
version = "0.1.0"
authors = ["Francois Garillot <francois@mystenlabs.com>"]
edition = "2021"
description = "Generates a method to name enum variants."
license = "Apache-2.0"
repository = "https://github.com/mystenlabs/mysten-infra"
publish = ["crates-io"]

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.47"
quote = "1.0.20"
syn = "1.0.102"
