[package]
name = "mysten-network"
version = "0.2.0"
license = "Apache-2.0"
edition = "2021"
authors = ["Brandon Williams <brandon@mystenlabs.com>"]
description = "Mysten's network tooling"
repository = "https://github.com/mystenlabs/mysten-infra"
publish = ["crates-io"]

[dependencies]
bincode = "1.3.3"
bytes = "1.2.1"
eyre = "0.6.8"
futures = "0.3.21"
http = "0.2.8"
multiaddr = "0.15.0"
serde = { version = "1.0.140", features = ["derive"] }
tokio = { version = "1.21.2", features = ["sync", "rt", "macros"] }
tokio-stream = { version = "0.1.11", features = ["net"] }
tonic = { version = "0.8.2", features = ["transport"] }
tonic-health = "0.7.0"
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.3.4", features = ["trace", "set-header", "propagate-header"] }
tracing = "0.1.37"
