[package]
name = "mysten-network"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
bincode = "1.3.3"
bytes = "1.2.1"
eyre = "0.6.8"
futures = "0.3.21"
http = "0.2.8"
multiaddr = "0.14.0"
serde = { version = "1.0.140", features = ["derive"] }
tokio = { version = "1.20.1", features = ["sync", "rt", "macros"] }
tokio-stream = { version = "0.1.9", features = ["net"] }
tonic = { version = "0.7.2", features = ["transport"] }
tonic-health = "0.6.0"
tower = { version = "0.4.13", features = ["full"] }
tower-http = { version = "0.3.4", features = ["trace", "set-header", "propagate-header"] }
tracing = "0.1.36"
