[package]
name = "mysten-network"
version = "0.1.0"
license = "Apache-2.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.56"
bincode = "1.3.3"
bytes = "1.1.0"
multiaddr = "0.14.0"
futures = "0.3.21"
serde = { version = "1.0.137", features = ["derive"] }
tokio = { version = "1.17.0", features = ["sync", "rt", "macros"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { version = "0.7", features = ["transport"] }
tonic-health = "0.6.0"
tower = { version = "0.4", features = ["full"] }
pin-project = "1.0.10"
