[package]
name = "mysten-util-mem"
version = "0.11.0"
authors = ["Parity Technologies <admin@parity.io>", "Andrew Schran <aschran@mystenlabs.com>"]
repository = "https://github.com/mystenlabs/mysten-infra"
description = "Collection of memory related utilities"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.56.1"
publish = false

[dependencies]
cfg-if = "1.0.0"
hashbrown = { version = "0.12", optional = true }
mysten-util-mem-derive = { path = "../mysten-util-mem-derive", version = "0.1" }
impl-trait-for-tuples = "0.2.0"
fastcrypto = { git = "https://github.com/MystenLabs/fastcrypto", rev = "bbb2d02a7a64c27314721748cc4d015b00490dbe" }
indexmap = { version = "1.9.1", features = ["serde"] }
roaring = "0.10.0"
ed25519-consensus = { version = "2.0.1", features = ["serde"] }

smallvec = { version = "1.10.0", optional = true }
parking_lot = { version = "0.12.0", optional = true }
once_cell = "1.16.0"

[features]
default = ["std", "hashbrown", "smallvec", "estimate-heapsize"]
std = ["parking_lot"]
# Full estimate: no call to allocator
estimate-heapsize = []
