name: Documentation

on:
  push:
    branches: [ main, extensions ]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


jobs:
  spelling:
    name: Lint documentation
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Spell Check Docs
      uses: crate-ci/typos@master
      with:
        files: ./*.md
        isolated: true
