[package]
name = "component"
version = "0.1.0"
license = "Apache-2.0"
authors = ["Laura Makdah <laura@mystenlabs.com>"]
description = "library for resilient component supervision"
repository = "https://github.com/mystenlabs/mysten-infra"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.15.0", features = ["sync", "macros", "rt", "rt-multi-thread"] }
async-trait = "0.1.52"
anyhow = "1.0.55"
